name: .NET CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Restore Packages
      run: nuget restore CalculatorApp.csproj

    - name: Build Project
      run: msbuild CalculatorApp.csproj /p:Configuration=Release
